#!/bin/bash
echo "gaspol-video loaded. Skills available:"
echo "  video-full        — end-to-end pipeline (brainstorm → script → images → video → post → package)"
echo "  video-brainstorm  — Phase 1: brainstorm, cast, product, location, domain research"
echo "  video-script      — Phase 2-3.5: script, scene breakdown, reference collection"
echo "  video-image       — Phase 4: NB2 asset library + scene keyframes"
echo "  video-explainer   — Phase 4.5: Remotion shots for scenes that must be readable"
echo "  video-gen         — Phase 5: VEO / Seedance / Kling prompts (with image review)"
echo "  video-post        — Phase 6: voice-over, edit, SFX, subtitles, music, final mix"
echo "  video-package     — Phase 7: title, thumbnail bets, description"
echo "  video-validate    — unified validator (--script / --image / --video / --refs / --post / --all)"
echo "  video-add-platform — scaffold new AI video platform support"
echo ""
echo "Agents available:"
echo "  video-engine-agent    — subagent for batch/complex video production"
echo "  video-prompt-reviewer — independent validator for NB2/VEO prompt batches"
echo ""
echo "REMINDER: Read reference/global-promo-config.md FIRST for any prompt generation."
echo "Phase 6-7 need ffmpeg on PATH and ELEVENLABS_API_KEY / ASSEMBLYAI_API_KEY in .env."
echo "Anything missing degrades loudly and names what it could not do — nothing is skipped silently."
