#!/bin/bash
echo "gaspol-video loaded. Skills available:"
echo "  video-full        — end-to-end pipeline (brainstorm → script → images → video)"
echo "  video-brainstorm  — Phase 1: brainstorm, cast, product, location, domain research"
echo "  video-script      — Phase 2-3.5: script, scene breakdown, reference collection"
echo "  video-image       — Phase 4: NB2 asset library + scene keyframes"
echo "  video-gen         — Phase 5: VEO video prompts (with image review)"
echo "  video-validate    — unified validator (--script / --image / --video / --refs / --all)"
echo "  video-add-platform — scaffold new AI video platform support"
echo ""
echo "Agents available:"
echo "  video-engine-agent    — subagent for batch/complex video production"
echo "  video-prompt-reviewer — independent validator for NB2/VEO prompt batches"
echo ""
echo "REMINDER: Read reference/global-promo-config.md FIRST for any prompt generation."
