/**
 * Create a Remotion workspace inside a video project, on first use.
 *
 *   node templates/remotion/scaffold.mjs <project-dir>
 *
 * The workspace lives in {project}/shots/, not in this plugin: node_modules belongs to the
 * project it renders, and one workspace per client keeps their brand and their output apart.
 *
 * Writes package.json, remotion.config.ts, src/, and copies the shot template plus a
 * brand.json placeholder. Never runs npm install itself — that is the user's call and their
 * bandwidth.
 */

import { mkdir, readFile, readdir, writeFile, access } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));

const PACKAGE_JSON = {
  name: "gaspol-video-shots",
  private: true,
  version: "1.0.0",
  type: "module",
  scripts: {
    gen: "node scripts/gen-registry.mjs",
    studio: "node scripts/gen-registry.mjs && remotion studio src/index.ts",
    render: "node scripts/gen-registry.mjs && node scripts/render-all.mjs",
    still: "node scripts/gen-registry.mjs && node scripts/render-all.mjs --still",
  },
  dependencies: {
    "@remotion/cli": "^4.0.0",
    "@remotion/bundler": "^4.0.0",
    "@remotion/renderer": "^4.0.0",
    "@remotion/captions": "^4.0.0",
    remotion: "^4.0.0",
    react: "^18.3.1",
    "react-dom": "^18.3.1",
  },
};

const REMOTION_CONFIG = `import { Config } from "@remotion/cli/config";

Config.setVideoImageFormat("jpeg");
Config.setOverwriteOutput(true);
// Explainer shots are composited over clips, so a transparent shot needs ProRes 4444.
// Opaque cutaways render as h264 and stay small.
`;

const INDEX_TS = `import { registerRoot } from "remotion";
import { RemotionRoot } from "./Root";

registerRoot(RemotionRoot);
`;

const ROOT_TSX = `import React from "react";
import { Composition } from "remotion";
import { shots } from "./registry.gen";

// One <Composition> per shot in src/shots/**/*.tsx. registry.gen.tsx is
// generated by scripts/gen-registry.mjs (run via "npm run gen") — never edit it.
export const RemotionRoot: React.FC = () => (
  <>
    {shots.map(({ Comp, config }) => (
      <Composition
        key={config.id}
        id={config.id}
        component={Comp}
        durationInFrames={config.durationInFrames}
        fps={config.fps}
        width={config.width}
        height={config.height}
      />
    ))}
  </>
);
`;

const REGISTRY_GEN_PLACEHOLDER = `// AUTO-GENERATED by scripts/gen-registry.mjs — do not edit.
// Placeholder so Studio can open before "npm run gen" has scanned src/shots.
import type React from "react";

export const shots: { Comp: React.FC; config: any }[] = [];
`;

async function exists(p) {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

async function main() {
  const project = process.argv[2];
  if (!project) {
    console.error("usage: node templates/remotion/scaffold.mjs <project-dir>");
    process.exit(2);
  }
  const root = path.join(project, "shots");
  if (await exists(path.join(root, "package.json"))) {
    console.log(`workspace already exists at ${root} — nothing was overwritten`);
    return;
  }

  await mkdir(path.join(root, "src", "shots"), { recursive: true });
  await mkdir(path.join(root, "src", "lib"), { recursive: true });
  await mkdir(path.join(root, "scripts"), { recursive: true });
  await mkdir(path.join(root, "public"), { recursive: true });
  await mkdir(path.join(root, "out"), { recursive: true });

  await writeFile(path.join(root, "package.json"), `${JSON.stringify(PACKAGE_JSON, null, 2)}\n`);
  await writeFile(path.join(root, "remotion.config.ts"), REMOTION_CONFIG);
  await writeFile(path.join(root, "src", "index.ts"), INDEX_TS);
  await writeFile(path.join(root, "src", "Root.tsx"), ROOT_TSX);
  await writeFile(path.join(root, "src", "registry.gen.tsx"), REGISTRY_GEN_PLACEHOLDER);
  await writeFile(
    path.join(root, "src", "shots", "MetricReveal.tsx"),
    await readFile(path.join(here, "Shot.template.tsx"), "utf8"),
  );
  await writeFile(
    path.join(root, "src", "shots", "brand.json"),
    await readFile(path.join(here, "brand.json"), "utf8"),
  );

  const libDir = path.join(here, "lib");
  for (const name of await readdir(libDir)) {
    await writeFile(path.join(root, "src", "lib", name), await readFile(path.join(libDir, name), "utf8"));
  }
  const scriptsDir = path.join(here, "scripts");
  for (const name of await readdir(scriptsDir)) {
    await writeFile(path.join(root, "scripts", name), await readFile(path.join(scriptsDir, name), "utf8"));
  }

  console.log(`scaffolded ${root}`);
  console.log("next:");
  console.log(`  1. write ${path.join(root, "src", "shots", "brand.json")} from strategic-brief.md`);
  console.log(`  2. cd ${root} && npm install    (about 300MB, once per project)`);
  console.log("  3. npm run studio               to see every shot in src/shots/");
  console.log("  4. npm run render <ShotId>      renders out/<ShotId>.mp4 (or .mov if transparent)");
}

main().catch((err) => {
  console.error(`scaffold: ${err.message}`);
  process.exit(1);
});
